# Generated by Django 6.0 on 2025-12-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='temp123', max_length=255),
            preserve_default=False,
        ),
    ]
